# Generated by Django 5.1.15 on 2026-03-06 14:51

import findings.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Evidence",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "file",
                    models.FileField(upload_to=findings.models.evidence_upload_path),
                ),
                ("caption", models.CharField(blank=True, default="", max_length=300)),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["uploaded_at"],
            },
        ),
        migrations.CreateModel(
            name="Finding",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=300)),
                (
                    "description",
                    models.TextField(
                        help_text="Detailed description of the finding (Markdown)."
                    ),
                ),
                (
                    "recommendations",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Recommended remediation steps (Markdown).",
                    ),
                ),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("critical", "Critical"),
                            ("high", "High"),
                            ("medium", "Medium"),
                            ("low", "Low"),
                            ("informational", "Informational"),
                        ],
                        default="medium",
                        max_length=15,
                    ),
                ),
                (
                    "cvss_score",
                    models.DecimalField(
                        blank=True,
                        decimal_places=1,
                        help_text="CVSS 3.1 base score (0.0 – 10.0).",
                        max_digits=3,
                        null=True,
                    ),
                ),
                (
                    "cvss_vector",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="CVSS 3.1 vector string.",
                        max_length=200,
                    ),
                ),
                (
                    "affected_assets",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Affected hosts, IPs, URLs — one per line.",
                    ),
                ),
                (
                    "references",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="External references, CVE IDs — one per line.",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("open", "Open"),
                            ("in_progress", "In Progress"),
                            ("remediated", "Remediated"),
                            ("closed", "Closed"),
                            ("accepted", "Risk Accepted"),
                        ],
                        default="open",
                        max_length=15,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
