# Generated by Django 5.1.15 on 2026-03-09 19:17

import findings.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("findings", "0003_asset_finding_asset"),
    ]

    operations = [
        migrations.AlterField(
            model_name="evidence",
            name="file",
            field=models.FileField(
                upload_to=findings.models.evidence_upload_path,
                validators=[findings.models.validate_evidence_file],
            ),
        ),
    ]
