# Generated by Django 5.1.15 on 2026-03-13 14:22

import django.core.validators
import django.db.models.deletion
import findings.models
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('findings', '0005_reporttemplate_generatedreport'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='evidence',
            name='file',
            field=models.FileField(max_length=500, upload_to=findings.models.evidence_upload_path, validators=[findings.models.validate_evidence_file]),
        ),
        migrations.AlterField(
            model_name='finding',
            name='cvss_score',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='CVSS 3.1 base score (0.0 – 10.0).', max_digits=3, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.0')), django.core.validators.MaxValueValidator(Decimal('10.0'))]),
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Client / organization name.', max_length=300)),
                ('description', models.TextField(blank=True, default='', help_text='Additional notes about this client.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clients_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='asset',
            name='client',
            field=models.ForeignKey(blank=True, help_text='The client this asset belongs to.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assets', to='findings.client'),
        ),
    ]
