# Generated by Django 5.1.15 on 2026-03-13 15:09

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('findings', '0006_alter_evidence_file_alter_finding_cvss_score_client_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FindingHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('created', 'Created'), ('updated', 'Updated'), ('deleted', 'Deleted')], max_length=10)),
                ('changes', models.JSONField(blank=True, default=dict, help_text='Dict of changed fields: {"field": {"old": ..., "new": ...}}')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='finding_changes', to=settings.AUTH_USER_MODEL)),
                ('finding', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='findings.finding')),
            ],
            options={
                'verbose_name_plural': 'finding histories',
                'ordering': ['-timestamp'],
            },
        ),
    ]
