# Generated by Django 5.1.15 on 2026-03-20 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('findings', '0007_findinghistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='finding',
            name='impact',
            field=models.TextField(blank=True, default='', help_text='Impact analysis of the finding (Markdown).'),
        ),
    ]
