# Generated by Django 5.1.15 on 2026-03-26 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('findings', '0008_add_impact_field'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asset',
            name='is_in_scope',
        ),
    ]
