# Generated by Django 5.1.15 on 2026-03-09 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("admin", "Admin"),
                    ("analyst", "Analyst"),
                    ("viewer", "Viewer"),
                ],
                default="viewer",
                help_text="Determines the user's permission level.",
                max_length=10,
            ),
        ),
    ]
