<script setup lang="ts">
import { ref, computed, onMounted } from 'vue'
import api, { downloadMedia } from '../api/client'
import { useAuthStore } from '../stores/auth'
import type { GeneratedReport } from '../types'

const auth = useAuthStore()
const error = ref('')
const reports = ref<GeneratedReport[]>([])
const loading = ref(true)

const canDelete = computed(() => auth.isAdmin)

async function fetchReports() {
  loading.value = true
  try {
    const { data } = await api.get('/reports/')
    reports.value = data.results || data
  } catch {
    error.value = 'Failed to load reports.'
  } finally {
    loading.value = false
  }
}

function downloadReport(report: GeneratedReport) {
  if (report.file) {
    downloadMedia(report.file, report.name + '.pdf')
  }
}

async function deleteReport(report: GeneratedReport) {
  if (!confirm(`Delete report "${report.name}"?`)) return
  try {
    await api.delete(`/reports/${report.id}/`)
    reports.value = reports.value.filter(r => r.id !== report.id)
  } catch {
    error.value = 'Failed to delete report.'
  }
}

function formatDateTime(dateStr: string): string {
  return new Date(dateStr).toLocaleString()
}

onMounted(fetchReports)
</script>

<template>
  <div>
    <div class="flex-between mb-2">
      <h1>Reports</h1>
    </div>

    <div v-if="error" class="alert alert-error mb-2">{{ error }}</div>
    <div v-if="loading" class="text-muted text-center mt-3">Loading reports…</div>

    <template v-else>
      <div v-if="reports.length === 0" class="card">
        <p class="text-muted text-center">No reports generated yet. Generate reports from the Findings page.</p>
      </div>
      <div v-else class="card">
        <div class="table-container">
          <table>
            <thead>
              <tr>
                <th>Report Name</th>
                <th>Findings</th>
                <th>Generated By</th>
                <th>Date</th>
                <th style="width: 160px">Actions</th>
              </tr>
            </thead>
            <tbody>
              <tr v-for="r in reports" :key="r.id">
                <td style="font-weight: 500; max-width: 400px; overflow: hidden; text-overflow: ellipsis; white-space: nowrap">{{ r.name }}</td>
                <td class="text-muted">{{ r.finding_count }}</td>
                <td class="text-muted">{{ r.generated_by_username || '—' }}</td>
                <td class="text-muted">{{ formatDateTime(r.created_at) }}</td>
                <td>
                  <div class="flex gap-1">
                    <button class="btn btn-primary btn-sm" @click="downloadReport(r)">⬇ Download</button>
                    <button v-if="canDelete" class="btn btn-danger btn-sm" @click="deleteReport(r)">Delete</button>
                  </div>
                </td>
              </tr>
            </tbody>
          </table>
        </div>
      </div>
    </template>
  </div>
</template>
